apiVersion: "aadpodidentity.k8s.io/v1"
kind: AzureIdentity
metadata:
  name: ${INGRESS_MI_NAME}
  namespace: ingress
  annotations:
    aadpodidentity.k8s.io/Behavior: namespaced
spec:
  type: 0
  resourceID: ${INGRESS_MI_RESOURCE_ID}
  clientID: ${INGRESS_MI_CLIENT_ID}
---
apiVersion: "aadpodidentity.k8s.io/v1"
kind: AzureIdentityBinding
metadata:
  name: ${INGRESS_MI_NAME}-binding
  namespace: ingress
spec:
  azureIdentity: ${INGRESS_MI_NAME}
  selector: ${INGRESS_MI_NAME}
