# Hello World Test Secret in cluster KV
apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: cluster-kv
  namespace: ingress
  labels:
    aadpodidbinding: ${INGRESS_MI_NAME}
spec:
  provider: azure
  parameters:
    usePodIdentity: "true"
    keyvaultName: ${CLUSTER_KV_NAME}
    tenantId: ${AKS_TENANT_ID}
    objects: | # mounted
      array:
        - |
          objectName: hello
          objectType: secret
---
# TLS Cert in another resource group
apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: ingress-tls-${AKS_ENV_NAME}-wildcard
  namespace: ingress
  labels:
    aadpodidbinding: ${INGRESS_MI_NAME}
spec:
  provider: azure
  secretObjects:  # sync'd with k8s secrets
  - secretName: ingress-tls-${AKS_ENV_NAME}-wildcard
    type: kubernetes.io/tls
    data:
    - objectName: ${INGRESS_TLS_CERT_NAME}
      key: tls.key
    - objectName: ${INGRESS_TLS_CERT_NAME}
      key: tls.crt
  parameters:
    usePodIdentity: "true"
    keyvaultName: ${INGRESS_TLS_KEY_VAULT_NAME}
    objects: |
      array:
        - |
          objectName: ${INGRESS_TLS_CERT_NAME}
          objectType: secret
    tenantId: ${AKS_TENANT_ID}
---
# TLS Cert in another resource group
apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: ingress-tls-${AKS_ENV_NAME}
  namespace: ingress
  labels:
    aadpodidbinding: ${INGRESS_MI_NAME}
spec:
  provider: azure
  secretObjects:  # sync'd with k8s secrets
  - secretName: ingress-tls-${AKS_ENV_NAME}
    type: kubernetes.io/tls
    data:
    - objectName: ${AKS_ENV_NAME}-cloudkube
      key: tls.key
    - objectName: ${AKS_ENV_NAME}-cloudkube
      key: tls.crt
  parameters:
    usePodIdentity: "true"
    keyvaultName: ${INGRESS_TLS_KEY_VAULT_NAME}
    objects: |
      array:
        - |
          objectName: ${AKS_ENV_NAME}-cloudkube
          objectType: secret
    tenantId: ${AKS_TENANT_ID}
