# Test Secret (cluster KV)
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: cluster-kv
  namespace: ${INGRESS_NAMESPACE}
spec:
  provider: azure
  parameters:
    useVMManagedIdentity: "true"
    userAssignedIdentityID: ${KUBELET_MI_CLIENT_ID}
    keyvaultName: ${CLUSTER_KV_NAME}
    tenantId: ${AKS_TENANT_ID}
    objects: |
      array:
        - |
          objectName: hello
          objectType: secret
---
# Wildcard Cert
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: ingress-tls-${AKS_ENV_NAME}-wildcard
  namespace: ${INGRESS_NAMESPACE}
spec:
  provider: azure
  secretObjects:
  - secretName: ingress-tls-${AKS_ENV_NAME}-wildcard
    type: kubernetes.io/tls
    data:
    - objectName: wildcard-${AKS_ENV_NAME}-cloudkube
      key: tls.key
    - objectName: wildcard-${AKS_ENV_NAME}-cloudkube
      key: tls.crt
  parameters:
    useVMManagedIdentity: "true"
    userAssignedIdentityID: ${KUBELET_MI_CLIENT_ID}
    keyvaultName: cloudkube-${AKS_ENV_NAME}-kv
    objects: |
      array:
        - |
          objectName: wildcard-${AKS_ENV_NAME}-cloudkube
          objectType: secret
    tenantId: ${AKS_TENANT_ID}
---
# Root Cert
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: ingress-tls-${AKS_ENV_NAME}
  namespace: ${INGRESS_NAMESPACE}
spec:
  provider: azure
  secretObjects:
  - secretName: ingress-tls-${AKS_ENV_NAME}
    type: kubernetes.io/tls
    data:
    - objectName: ${AKS_ENV_NAME}-cloudkube
      key: tls.key
    - objectName: ${AKS_ENV_NAME}-cloudkube
      key: tls.crt
  parameters:
    useVMManagedIdentity: "true"
    userAssignedIdentityID: ${KUBELET_MI_CLIENT_ID}
    keyvaultName: cloudkube-${AKS_ENV_NAME}-kv
    objects: |
      array:
        - |
          objectName: ${AKS_ENV_NAME}-cloudkube
          objectType: secret
    tenantId: ${AKS_TENANT_ID}
