apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world
  namespace: ingress
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello-world
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      nodeSelector:
        workloadType: user
      containers:
      - name: hello-world
        image: julieio/hello:0.2.1
        ports:
        - containerPort: 3000
        env:
        - name: HELLO_GREETING
          value: "Hi"
        - name: HELLO_NAME
          value: ${AKS_ENV_HOSTNAME}
        - name: EARTH_COLOR
          value: "#00c2ca"
        - name: PORT
          value: "3000"